/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CoverRouteImport } from './routes/cover'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as EventsRouteImport } from './routes/events'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TokenRouteImport } from './routes/token'
import { Route as ApiCalendarRouteImport } from './routes/api.calendar'
import { Route as ApiDeskRouteImport } from './routes/api.desk'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api.openapi[.]json'
import { Route as ApiPendingRouteImport } from './routes/api.pending'
import { Route as ApiTapeRouteImport } from './routes/api.tape'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsTickerRouteImport } from './routes/events.$ticker'
import { Route as ApiTickerTickerRouteImport } from './routes/api.ticker.$ticker'
import { Route as ApiWirePostRouteImport } from './routes/api.wire.post'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverRoute = CoverRouteImport.update({
  id: '/cover',
  path: '/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarRoute = ApiCalendarRouteImport.update({
  id: '/api/calendar',
  path: '/api/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPendingRoute = ApiPendingRouteImport.update({
  id: '/api/pending',
  path: '/api/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapeRoute = ApiTapeRouteImport.update({
  id: '/api/tape',
  path: '/api/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsTickerRoute = EventsTickerRouteImport.update({
  id: '/$ticker',
  path: '/$ticker',
  getParentRoute: () => EventsRoute,
} as any)
const ApiTickerTickerRoute = ApiTickerTickerRouteImport.update({
  id: '/api/ticker/$ticker',
  path: '/api/ticker/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWirePostRoute = ApiWirePostRouteImport.update({
  id: '/api/wire/post',
  path: '/api/wire/post',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/cover': typeof CoverRoute
  '/docs': typeof DocsRoute
  '/events': typeof EventsRouteWithChildren
  '/paper': typeof PaperRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/token': typeof TokenRoute
  '/api/calendar': typeof ApiCalendarRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/pending': typeof ApiPendingRoute
  '/api/tape': typeof ApiTapeRoute
  '/events/$ticker': typeof EventsTickerRoute
  '/events/': typeof EventsIndexRoute
  '/api/ticker/$ticker': typeof ApiTickerTickerRoute
  '/api/wire/post': typeof ApiWirePostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/cover': typeof CoverRoute
  '/docs': typeof DocsRoute
  '/paper': typeof PaperRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/token': typeof TokenRoute
  '/api/calendar': typeof ApiCalendarRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/pending': typeof ApiPendingRoute
  '/api/tape': typeof ApiTapeRoute
  '/events/$ticker': typeof EventsTickerRoute
  '/events': typeof EventsIndexRoute
  '/api/ticker/$ticker': typeof ApiTickerTickerRoute
  '/api/wire/post': typeof ApiWirePostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/cover': typeof CoverRoute
  '/docs': typeof DocsRoute
  '/events': typeof EventsRouteWithChildren
  '/paper': typeof PaperRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/token': typeof TokenRoute
  '/api/calendar': typeof ApiCalendarRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/pending': typeof ApiPendingRoute
  '/api/tape': typeof ApiTapeRoute
  '/events/$ticker': typeof EventsTickerRoute
  '/events/': typeof EventsIndexRoute
  '/api/ticker/$ticker': typeof ApiTickerTickerRoute
  '/api/wire/post': typeof ApiWirePostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/cover'
    | '/docs'
    | '/events'
    | '/paper'
    | '/privacy'
    | '/sitemap.xml'
    | '/status'
    | '/terms'
    | '/token'
    | '/api/calendar'
    | '/api/desk'
    | '/api/health'
    | '/api/openapi.json'
    | '/api/pending'
    | '/api/tape'
    | '/events/$ticker'
    | '/events/'
    | '/api/ticker/$ticker'
    | '/api/wire/post'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/cover'
    | '/docs'
    | '/paper'
    | '/privacy'
    | '/sitemap.xml'
    | '/status'
    | '/terms'
    | '/token'
    | '/api/calendar'
    | '/api/desk'
    | '/api/health'
    | '/api/openapi.json'
    | '/api/pending'
    | '/api/tape'
    | '/events/$ticker'
    | '/events'
    | '/api/ticker/$ticker'
    | '/api/wire/post'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/cover'
    | '/docs'
    | '/events'
    | '/paper'
    | '/privacy'
    | '/sitemap.xml'
    | '/status'
    | '/terms'
    | '/token'
    | '/api/calendar'
    | '/api/desk'
    | '/api/health'
    | '/api/openapi.json'
    | '/api/pending'
    | '/api/tape'
    | '/events/$ticker'
    | '/events/'
    | '/api/ticker/$ticker'
    | '/api/wire/post'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  CoverRoute: typeof CoverRoute
  DocsRoute: typeof DocsRoute
  EventsRoute: typeof EventsRouteWithChildren
  PaperRoute: typeof PaperRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  TokenRoute: typeof TokenRoute
  ApiCalendarRoute: typeof ApiCalendarRoute
  ApiDeskRoute: typeof ApiDeskRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiPendingRoute: typeof ApiPendingRoute
  ApiTapeRoute: typeof ApiTapeRoute
  ApiTickerTickerRoute: typeof ApiTickerTickerRoute
  ApiWirePostRoute: typeof ApiWirePostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover': {
      id: '/cover'
      path: '/cover'
      fullPath: '/cover'
      preLoaderRoute: typeof CoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar': {
      id: '/api/calendar'
      path: '/api/calendar'
      fullPath: '/api/calendar'
      preLoaderRoute: typeof ApiCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pending': {
      id: '/api/pending'
      path: '/api/pending'
      fullPath: '/api/pending'
      preLoaderRoute: typeof ApiPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tape': {
      id: '/api/tape'
      path: '/api/tape'
      fullPath: '/api/tape'
      preLoaderRoute: typeof ApiTapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$ticker': {
      id: '/events/$ticker'
      path: '/$ticker'
      fullPath: '/events/$ticker'
      preLoaderRoute: typeof EventsTickerRouteImport
      parentRoute: typeof EventsRoute
    }
    '/api/ticker/$ticker': {
      id: '/api/ticker/$ticker'
      path: '/api/ticker/$ticker'
      fullPath: '/api/ticker/$ticker'
      preLoaderRoute: typeof ApiTickerTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wire/post': {
      id: '/api/wire/post'
      path: '/api/wire/post'
      fullPath: '/api/wire/post'
      preLoaderRoute: typeof ApiWirePostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsTickerRoute: typeof EventsTickerRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsTickerRoute: EventsTickerRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  CoverRoute: CoverRoute,
  DocsRoute: DocsRoute,
  EventsRoute: EventsRouteWithChildren,
  PaperRoute: PaperRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  TokenRoute: TokenRoute,
  ApiCalendarRoute: ApiCalendarRoute,
  ApiDeskRoute: ApiDeskRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiPendingRoute: ApiPendingRoute,
  ApiTapeRoute: ApiTapeRoute,
  ApiTickerTickerRoute: ApiTickerTickerRoute,
  ApiWirePostRoute: ApiWirePostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
